### ISSUE TITLE
extract($_POST,EXTR_OVERWRITE); is bad practice and possibly insecure

### ISSUE THREAD

**Issue by Petah** [PayGate/sample-code-php#10]
https://github.com/PayGate/sample-code-php/blob/master/PayHost/singlePayment/cardPayment/index.php#L20

Using `extract($_POST,EXTR_OVERWRITE);` is bad practice and possibly insecure. It essentially re-implements a long deprecated and removed function of PHP which is `register_globals`.

**Comment by RBAtkins0n** [comment]
Thanks for reporting this, the sample code is due for an update.
Will close once complete.
