### ISSUE TITLE
DATA_CHK Error when Return URL contain '&'

### ISSUE THREAD

**Issue by arslan7720** [PayGate/sample-code-php#3]
Hello. 
I have an issue using the Paygate web3,
I have downloaded the Php sample code and when i change the Return url to include the '&' character in the url like (http://localhost/PayWeb3/result.php&id=22) it give DATA_CHK error().
The example code work fine if i remove the '&' character from the Return url, is there any solution for it, and i need to use '&' character its compulsory.

**Comment by DeagleDaemon** [comment]
Hi!

I've had a look and it appears to be an issue when sanitizing the $_POST vars when we setup the initiate request and create the checksum in the sample code. I'll have a look and see if I can patch it.

Thanks for the heads up!

**Comment by DeagleDaemon** [comment]
Sorted the issue. The values being sent in the cURL post were not being urlencoded.
